name: gen docs

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  genDocs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies node
        run: npm ci

      - name: Generate gitbook pages
        run: npm run generate:gitbook

      - name: Check if docs changed
        id: diff
        run: |
          git add -f docs swagger
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Push docs to gitbook
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B gitbook
          git add -f docs
          git add -f swagger
          GIT_COMMIT_HASH=$(git rev-parse --short HEAD@{u} || git rev-parse --short HEAD)
          git commit -m "[ACTION COMMIT] update docs master (${GIT_COMMIT_HASH})"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/nodewalker/fake-store-api.git gitbook --force

      - name: No changes â€” skipping push
        if: steps.diff.outputs.changed == 'false'
        run: echo "Docs unchanged. Skipping push."
